language: go
before_script:
  - go vet $(go list ./... | grep -v /vendor/)
go:
  - 1.7
  - 1.8
  - 1.9
  - tip
install:
  - go get -v github.com/onsi/ginkgo/ginkgo
  - go get -v github.com/onsi/gomega
  - go get -v golang.org/x/crypto/ssh
  - go get -v -t ./...
  - export PATH=$PATH:$HOME/gopath/bin

script: ginkgo -r

